name:                         Rust test

on:
  pull_request:
  push:
    branches:
      - main
      - stable

jobs:
  check:
    name:                     Cargo test
    runs-on:                  ubuntu-latest
    steps:

      - name:                 Cancel Previous Runs
        uses:                 styfle/cancel-workflow-action@0.12.1
        with:
          access_token:       ${{ github.token }}

      - name:                 Checkout sources
        uses:                 actions/checkout@v4.2.2
        with:
          fetch-depth:        50
          submodules:         'recursive'

      - name:                 Install Rust stable toolchain
        uses:                 actions-rs/toolchain@v1.0.7
        with:
          profile:            minimal
          toolchain:          stable
          override:           true

      - name:                 Install cargo-nextest
        uses:                 baptiste0928/cargo-install@v3
        with:
          crate:              cargo-nextest
          version:            0.9

      - name:                 Rust Cache
        uses:                 Swatinem/rust-cache@v2.7.5

      - name: cargo nextest (default)
        run: cargo nextest run

      - name: cargo nextest (no-default-features)
        run: cargo nextest run --no-default-features

      - name: cargo nextest (sr25519 feature)
        run: cargo nextest run --no-default-features --features sr25519
